### ISSUE TITLE
IndexError in mda function “ data = data[:, lambds!=0] ”

### ISSUE THREAD

**Issue by sydddl** [xinglab-ai/mda#1]
I Follow the "MDA analysis of the DNN features in classification task" in `demo_MDA.ipynb`, but I get 

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
     lambds = np.linalg.svd(data, full_matrices=False, compute_uv=False)
-->  data = data[:, lambds!=0]
    
IndexError: boolean index did not match indexed array along dimension 1; dimension is 2048 but corresponding boolean dimension is 16000
```

`testDataFeatures` shape is (16000, 2048,7,7), and after SVD the `lambds` shape is (16000, 2048,7). What should I change?

**Comment by xinglab-ai** [comment]
Thanks. Please reshape the data into a 2D matrix, i.e., your testdataFeatures should be of shape (16000, 100352), [2048X7X7=100352]. Please use numpy.reshape to do that.

**Comment by sydddl** [comment]
> Thanks. Please reshape the data into a 2D matrix, i.e., your testdataFeatures should be of shape (16000, 100352), [2048X7X7=100352]. Please use numpy.reshape to do that.

It doesn't work for me, now the lambds is (16000,), testDataFeatures is (16000, 100352).

```py
IndexError: boolean index did not match indexed array along dimension 1; dimension is 100352 but corresponding boolean dimension is 320
```

But when I try to chance mda code to match index `data = data[lambds!=0, :]` , the Yreg is two big (100352,100352) and will use 75G.

**Comment by xinglab-ai** [comment]
Hi, the two lines "lambds = np.linalg.svd(data, full_matrices=False, compute_uv=False)
    data = data[:, lambds!=0]" are for computing the principal components to reduce the computational burden.  You can compute the PCA of your data and give the first 400/500 principal components as input to MDA after commenting out these two lines. Please also make sure that there are no NAN values in your data. Thanks

**Comment by sydddl** [comment]
Thank for your help，I get it



---Original---
From: ***@***.***&gt;
Date: Thu, Jan 25, 2024 11:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xinglab-ai/mda] IndexError in mda function “ data = data[:, lambds!=0] ” (Issue #1)




 
Hi, the two lines "lambds = np.linalg.svd(data, full_matrices=False, compute_uv=False)
 data = data[:, lambds!=0]" are for computing the principal components to reduce the computational burden.  You can compute the PCA of your data and give the first 400/500 principal components as input to MDA after commenting out these two lines. Please also make sure that there are no NAN values in your data. Thanks
