### ISSUE TITLE
Adaptability to PyTorch-based models

### ISSUE THREAD

**Issue by fuzanhao** [xinglab-ai/mda#3]
Hi,

Thanks for the available code. 
Currently, I am dealing with deep learning models based on PyTorch. When I used the "mda" function, I noticed that it included "from umap.parametric_umap import ParametricUMAP", and this seemed to be only available for TensorFlow-based models. Are there any alternative choices?

Thanks

**Comment by tauhidstanford** [comment]
Hi,

You can use non-parametric UMAP from https://umap-learn.readthedocs.io/en/latest/ with similar analysis performance. 

Thanks.

**Comment by fuzanhao** [comment]
> Hi,
> 
> You can use non-parametric UMAP from https://umap-learn.readthedocs.io/en/latest/ with similar analysis performance.
> 
> Thanks.

Thanks for your reply. It works.

**Comment by IsDling** [comment]
> > Hi,
> > You can use non-parametric UMAP from https://umap-learn.readthedocs.io/en/latest/ with similar analysis performance.
> > Thanks.
> 
> Thanks for your reply. It works.

hello,can you share how to change the code using non-parametric UMAP?
